# NumPy Matrix + Pandas Assignment 


## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [1]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```


In [2]:
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```


In [4]:
print(arr.sum(axis = 1))

[ 6 15 24]


## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```


In [5]:
print(arr.sum(axis = 0))

[12 15 18]


## Q5. Extract Second Row

### Output
```python
[4 5 6]
```


In [9]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[1:2,0:3])

[[4 5 6]]


## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |


In [ ]:
import pandas as pd
a = pd.DataFrame({

    'Name': ['Raj','Amit','Neha','Priya'],
    'Marks': [80,70,90,85]

})

print(a)



## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```


In [ ]:
import pandas as pd
a = pd.DataFrame({

    'Name': ['Raj','Amit','Neha','Priya'],
    'Marks': [80,70,90,85]

})


a['Bonus'] = a['marks']+5
print(a)



## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```


In [ ]:
a = pd.DataFrame({
    "Name": ['Prem','Neha','Sautum','Priya','Ram']
    "Marks" : [60,90,69,85,70]
})

print(a[['Marks']>80])

## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```


In [ ]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Neha", "Raj", "Amit", "Emma"],
    "Marks": [25, 70, 80, 90, 22]
    
}

b = pd.DataFrame(a)
print(b.iloc[2])


## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```


In [ ]:
print(b)
print(b.iloc[1])

## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```


In [ ]:
print(b.iloc[2:4])

## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```


In [ ]:
# Write your code here

## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```


In [ ]:
import pandas as pd

a = {
    "Name": ["Alice", "Neha", "Raj", "Amit", "Emma"],
    "Marks": [25, 70, 80, 90, 22]
    
}

b = pd.DataFrame(a)
b.loc[3,'Marks'] = 75
print(b)


## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```


In [ ]:
a = pd.DataFrame({
    'Name': ['Neha','Priya','Raj','Amit'],
    'Marks':[90,85,80,75]
})

print(a.sort_values(by = 'Marks',ascending = False))