
# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


import numpy as np
arr = np.array([10,20,30,40,50])

print("Shape:,np.shape")
print("")

In [30]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


# for 2D array
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)




(5,)
1
5
int64
(3, 3)
2
9
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [14]:
import numpy as np
matrix = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [32]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[0])
print(arr[2])
print(arr[6])


#2D array
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr1[0,0])
print(arr1[0,2])
print(arr1[2,2])


1
3
7
1
3
9



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [33]:
arr = np.array([1,2,3,4,5,6])
print(arr[2:5])

#2D array
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr1[1:3,1:3])


[3 4 5]
[[5 6]
 [8 9]]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [40]:
arr = np.array([1,2,3,4,5])
print(arr[[1,3]])

#for 2d array
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr1[[0,1]])
print(arr1[:,[0,2,1]])





[2 4]
[[1 2 3]
 [4 5 6]]
[[1 3 2]
 [4 6 5]
 [7 9 8]]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [41]:
arr = np.array([23,14,78,13,10,8])
np.where(arr>15)
print(np.where(arr>15,arr,0))


#for 2d array
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

np.where(arr1>4)
print(np.where(arr1>4,arr1,0))


[23  0 78  0  0  0]
[[0 0 0]
 [0 5 6]
 [7 8 9]]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [42]:
arr = np.array([1,2,3,5,6])
print(arr+10)

arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr1+10)

[11 12 13 15 16]
[[11 12 13]
 [14 15 16]
 [17 18 19]]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [43]:
arr = np.array([2,3,45,67,46])

print(f"sum is:{arr.sum()}")
print(f"mean is:{arr.mean()}")
print(f"max is:{arr.max()}")
print(f"min is:{arr.min()}")

# for 2d array
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


print(f"sum is:{arr1.sum()}")
print(f"mean is:{arr1.mean()}")
print(f"max is:{arr1.max()}")
print(f"min is:{arr1.min()}")


sum is:163
mean is:32.6
max is:67
min is:2
sum is:45
mean is:5.0
max is:9
min is:1



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [44]:
arr = np.array([2,4,1,7,3,0])
print(np.sort(arr))


#for 2D array
arr1 = np.array([
    [18,12,3],
    [4,15,6],
    [7,28,9]
])

print(np.sort(arr1))



[0 1 2 3 4 7]
[[ 3 12 18]
 [ 4  6 15]
 [ 7  9 28]]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [45]:
arr1 = np.array([2,3,4,5,6])
arr2 = np.array([6,5,8,9,2])
np.concatenate((arr1,arr2))

np.vstack((arr1,arr2))

array([[2, 3, 4, 5, 6],
       [6, 5, 8, 9, 2]])